import { Component } from '@angular/core';
import { PortfolioContentComponent } from "../portfolio-content/portfolio-content.component";

@Component({
  selector: 'app-planning-for-instruction',
  imports: [PortfolioContentComponent],
  templateUrl: './planning-for-instruction.component.html',
  styleUrl: './planning-for-instruction.component.scss'
})
export class PlanningForInstructionComponent {
  public contentBlocks = [
    `
    <p>In writing <a target="_blank" href="https://docs.google.com/document/d/1ThepTUQYen6E6rIbYh36Zgs8Va_XTFhNXMcrWTPaZ2A/edit?tab=t.0" aria-label="Lesson Plan">Lesson Plan</a>, particularly for my Science Methods course, I have come to understand the importance of choosing anti-racist, culturally relevant, and responsive instructional strategies, as outlined in Standard 4, E. For example, in a lesson plan I created for first-grade students on the topic of vibration and sound, I intentionally selected resources and strategies that would engage all students and be accessible regardless of their cultural backgrounds. I used hands-on activities that allowed students to explore sound through vibration, such as using common materials from diverse cultural contexts, making the content relatable. Additionally, I incorporated visual aids and interactive demonstrations to ensure that students with varying language proficiency or learning needs could fully engage in the lesson. This approach allowed me to differentiate instruction effectively for individual students and groups, fostering an inclusive learning environment. Through this lesson, I aimed to meet each student’s learning goals by choosing strategies and resources that were no</p>
    <p>The <a target="_blank" href="https://docs.google.com/document/d/1VlLmFkesXbj9EmztCX21ifiZgG3ai3tKTE70CqP-EaQ/edit?tab=t.0" aria-label="Lesson">Lesson</a> I created for Theory to Practice aligns with Standard 4, E by incorporating anti-racist, culturally relevant, and responsive instructional strategies to meet the diverse needs of my students. I used language support tools like a word bank, sentence starters, and teacher examples to ensure the lesson was accessible to all learners. The lesson encourages students to explore their own cultures, identities, and experiences, allowing them the freedom to express themselves in a safe and supportive environment. By offering differentiated assignments and adjusting support based on individual needs, I ensured that every student could progress toward their learning goals. Additionally, using innovative digital resources demonstrated my commitment to creating an inclusive, culturally responsive learning environment where every student has the tools to succeed. This lesson exemplifies my ability to plan and execute culturally relevant and differentiated instruction, as required by Standard 4, E.</p>
    <p>As an outdoor kayaking, canoeing, and biking instructor for children ages 4-15, I learned the critical role that planning plays in achieving the unique learning goals of each student. Whether working with younger students by incorporating creative activities like drawing circles on the water with their kayak paddles, or challenging older students with more advanced tasks like racing and bike repair, I understood that planning must be tailored to meet the specific needs and abilities of each group. This experience helped me realize that planning is not just about structuring lessons but also about ensuring that every activity is inclusive, culturally relevant, and responsive to the diverse backgrounds of students. It reinforced the importance of using adaptive instructional strategies that consider students' individual needs, interests, and learning styles, which is a core aspect of Standard 4, E.
</p>
    <p>As I begin my student teaching, I aim to apply the same approach to planning, ensuring that each lesson aligns with students' learning goals while incorporating anti-racist, culturally relevant, and responsive strategies. I will focus on designing lessons that not only address academic content but also honor and integrate students' cultural backgrounds and experiences. My goal is to differentiate instruction by using varied resources, accommodations, and strategies to meet the needs of all students, ensuring that each has an equitable opportunity to succeed. I will continue to develop the skill of flexible lesson planning to ensure that all students feel valued and supported, achieving their individual learning objectives in an inclusive environment.</p>
    <p></p>
    <p></p>
    `
  ]
headerTitlePhrase: string|undefined = `
"The teacher plans how to achieve each student's learning goals by choosing anti-racist, culturally relevant, and responsive instructional strategies, accommodations, and resources to differentiate instruction for individuals and groups of learners." - Standard 4, E. `;
}
