import { Component } from '@angular/core';
import { PortfolioContentComponent } from "../portfolio-content/portfolio-content.component";

@Component({
  selector: 'app-racial-consciousness-and-reflection',
  imports: [PortfolioContentComponent],
  templateUrl: './racial-consciousness-and-reflection.component.html',
  styleUrl: './racial-consciousness-and-reflection.component.scss'
})
export class RacialConsciousnessAndReflectionComponent {
contentBlocks: string[] =[
  `
  <p>In my coursework, one significant project that demonstrates my understanding of racial consciousness and cultural content was a <a href='https://docs.google.com/presentation/d/1pNiw0n7azN1uzKAyII7_kxFkUWeZdnyBttYMuxvR4r0/edit?usp=sharing' aria-label='Chapter Presentation'>Chapter Presentation</a> I prepared for my Equity and Diversity class. I focused on the experiences of immigrant and refugee youth in schools, emphasizing the challenges they face, including societal exclusion, trauma, and separation from family. The presentation highlighted how students must feel a sense of safety and belonging to thrive in school, aligning with Standard 8, F. Through this project, I deepened my understanding of the importance of recognizing the histories, cultures, and perspectives of marginalized communities and integrating those insights into teaching practices. It reinforced the need for culturally responsive instruction and the critical role teachers play in creating an inclusive, supportive classroom environment where all students can succeed.
</p>
  <p>One of the most impactful assignments I completed in my coursework was a <a href='https://docs.google.com/presentation/d/1pP3wfQ4nLw-FA50ymPiJEHqT2Udt16M57bGQDcz2BUU/edit?usp=sharing' aria-label='Presentation'>Presentation</a> on the Roots of Racism. This assignment gave me the chance to deeply explore the history of slavery and understand how its effects continue to shape society today. It helped me realize how important it is for educators to recognize and acknowledge this history, as well as its ongoing impact on students. This experience directly connects to Standard 8, E, as it reinforced the need for educators to be aware of the diverse cultural backgrounds of their students and the systemic issues that affect them. By understanding the roots of racism, I gained a clearer view of the responsibility teachers have in creating inclusive, equitable environments where all students feel safe and valued. It highlighted the importance of promoting social justice and helping students think critically about race and inequality, which are essential in fostering an equitable learning environment.
</p>
  <p>Coming from a different country, I have had the privilege of working in both Turkey and the U.S., where I have encountered a wide range of student backgrounds. In Turkey, I worked with students aged 5 to 15, learning to adapt my teaching methods to their diverse cultural contexts. In the U.S., I teach at an elementary school where 90% of the student population are immigrants, many from Somali and other African communities. This experience has taught me how important it is to recognize and value each student’s unique cultural history and language. Additionally, I worked as an outdoor sports instructor and at an outdoor adventure summer camp, where most of the students came from white, upper-class families with significant financial means. This exposure allowed me to understand the impact of socioeconomic privilege on students’ educational experiences. These experiences have reinforced the need to incorporate diverse cultural perspectives, including Indigenous histories and languages, into my teaching. Understanding the worldviews and experiences of all my students—whether they come from immigrant, upper-class, or other backgrounds—has deepened my commitment to creating an inclusive, culturally responsive classroom.</p>
  <p>When I begin student teaching, my goal is to deepen my understanding of the cultural content, histories, and languages of Minnesota-based American Indian Tribal Nations and communities, in alignment with Standard 8, F. I plan to integrate Indigenous perspectives into my lessons while considering the diverse cultural, linguistic, and socioeconomic backgrounds of my students. Drawing from my experiences in Turkey, my work with immigrant students in the U.S., my time as an outdoor sports instructor, and my role at the outdoor adventure summer camp, I aim to create a classroom that promotes cultural awareness, respect, and inclusion. By incorporating Indigenous histories, languages, and perspectives into my teaching, I hope to foster an environment where all students, regardless of their background, feel valued, respected, and empowered to share their unique experiences.
</p>
  `
];
headerTitlePhrase: string|undefined = `
  "The teacher understands the cultural content, world view, concepts, and perspectives of Minnesota-based American Indian Tribal Nations and communities, including Indigenous histories and languages." Standard 8, F.
`;
}
