name: Build and Deploy Angular App

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci
        working-directory: ./   # root

      - name: Build Angular project
        run: npm run build -- --configuration production --base-href="/portfolio-safiie/"
        working-directory: ./   # root

      - name: Add SPA redirect
        run: cp dist/portfolio-safiie/index.html dist/portfolio-safiie/404.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist/portfolio-safiie

